-- begin KUKAZUE_TIER
alter table KUKAZUE_TIER add constraint FK_KUKAZUE_TIER_VATER foreign key (VATER_ID) references KUKAZUE_TIER(ID)^
alter table KUKAZUE_TIER add constraint FK_KUKAZUE_TIER_MUTTER foreign key (MUTTER_ID) references KUKAZUE_TIER(ID)^
create index IDX_KUKAZUE_TIER_VATER on KUKAZUE_TIER (VATER_ID)^
create index IDX_KUKAZUE_TIER_MUTTER on KUKAZUE_TIER (MUTTER_ID)^
-- end KUKAZUE_TIER
-- begin KUKAZUE_TIER_FILE_DESCRIPTOR_LINK
alter table KUKAZUE_TIER_FILE_DESCRIPTOR_LINK add constraint FK_KTFDL_TIER foreign key (TIER_ID) references KUKAZUE_TIER(ID)^
alter table KUKAZUE_TIER_FILE_DESCRIPTOR_LINK add constraint FK_KTFDL_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end KUKAZUE_TIER_FILE_DESCRIPTOR_LINK
-- begin KUKAZUE_SHOW_ERGEBNIS
alter table KUKAZUE_SHOW_ERGEBNIS add constraint FK_KUKAZUE_SHOW_ERGEBNIS_TIER foreign key (TIER_ID) references KUKAZUE_TIER(ID)^
alter table KUKAZUE_SHOW_ERGEBNIS add constraint FK_KUKAZUE_SHOW_ERGEBNIS_SHOW foreign key (SHOW_ID) references KUKAZUE_SHOW(ID)^
create index IDX_KUKAZUE_SHOW_ERGEBNIS_TIER on KUKAZUE_SHOW_ERGEBNIS (TIER_ID)^
create index IDX_KUKAZUE_SHOW_ERGEBNIS_SHOW on KUKAZUE_SHOW_ERGEBNIS (SHOW_ID)^
-- end KUKAZUE_SHOW_ERGEBNIS
